theme: minima
title: Ryan McKinney's Portfolio
description: Data Science Student at St. Bonaventure
author: Ryan McKinney
email: rwmckinney2006@gmail.com
header_pages:
  - about_me.md
  - projects.md
  - contact_me.md